language: elixir

elixir:
  - 1.4
  - 1.5
  - 1.6
otp_release:
  - 19.3
  - 20.3
  - 21.0
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.4
      otp_release: 21.0
sudo: false
script:
  - "MIX_ENV=test mix coveralls.travis"

notifications:
  email: false
